### ISSUE TITLE
[data-ingestion]: Support S3 providers other than AWS

### ISSUE THREAD

**Issue by kodemartin** [iotaledger/iota#5145]
## Description

As reported the configuration used in `iota-data-ingestion` for connecting to S3 is not compatible with providers other than AWS that offer compatible APIs.

The `iota_config::object_storage_config::ObjectStoreConfig` provides more options and thus could be used to this end.

@junwei0117 could you please provide a sample S3 configuration you provide for archival/backup?

**Comment by junwei0117** [comment]
here's the config for archive node in testnet

```
state-archive-read-config:
  - object-store-config:
      object-store: "S3"
      aws-endpoint: "https://fsn1.your-objectstorage.com"
      bucket: "iota-testnet-archive"
      aws-access-key-id: "K40......LEB"
      aws-secret-access-key: "inx......P1j"
      object-store-connection-limit: 20
    concurrency: 5
    use-for-pruning-watermark: true

```
