### ISSUE TITLE
Cleanup os variables in release.yml

### ISSUE THREAD

**Issue by Thoralf-M** [iotaledger/iota#5450]
Instead of setting them like now https://github.com/iotaledger/iota/blob/4e3e15c21c898b2f9078c98251d5e7db77ebae83/.github/workflows/release.yml#L70-L94
they should be included in the matrix, like this
```
     matrix:
        include:
          - os: self-hosted
            os-type: ubuntu-x86_64
          - os: ubuntu-24.04-arm
            os-type: ubuntu-arm64
          - os: macos-latest
            os-type: macos-arm64
          - os: windows-latest
            os-type: windows-x86_64
```
