### ISSUE TITLE
`TestCluster` ignores iota-names config on resume

### ISSUE THREAD

**Issue by samuel-rufi** [iotaledger/iota#7234]
## Bug description

It appears that if the TestCluster is stopped, and the iota-names config parameters are added to the persisted cluster configuration before it is resumed, the resumed cluster ignores the provided iota-names configuration.

It seems that the config loader defaults the iota-names config to `None` instead of reading the correct config.

## Relevant links

https://github.com/iotaledger/iota/issues/6806#issuecomment-2911529015

**Comment by Thoralf-M** [comment]
Do we have an example for how the config needs to look? Like the full node/client config file

**Comment by samuel-rufi** [comment]
@Thoralf-M  you can add the options now with https://github.com/iotaledger/iota/pull/7819 to the `fullnode.yaml` config file, which is offering the RPC service. You can also add this optionally to the validators if you like, as part of the network.yaml config.

```
iota-names-config:
  package-address: "0xb9d617f24c84826bf660a2f4031951678cc80c264aebc4413459fb2a95ada9ba"
  object-id: "0x07c59b37bd7d036bf78fa30561a2ab9f7a970837487656ec29466e817f879342"
  payments-package-address: "0x98b9b33b7c2347a8f4e8b8716fb4c7e6e1af846ec2ea063a47bba81ffe03b440"
  registry-id: "0xe00b2f2400c33b4dbd3081c4dcf2e289d0544caba23a3d130b264bd756403c07"
  reverse-registry-id: "0x1c1da17843cc453ad4079b05ce55e103b7a8cdd4db6ab42dc367b47ed6d8994d"
```
